'use client';

import { useState, useEffect } from 'react';
import { Task } from '@/types/agent';
import { getNocoData } from '@/lib/nocodb';

export default function TasksPage() {
    const [tasks, setTasks] = useState<Task[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isCreating, setIsCreating] = useState(false);

    useEffect(() => {
        const fetchTasks = async () => {
            let fetchedTasks = await getNocoData('Projects_Tasks');

            if (!fetchedTasks || fetchedTasks.length === 0) {
                fetchedTasks = [
                    { id: 'T-001', title: 'Initialize Main Platform Components', description: 'Create basic scaffold for backend architecture and NocoDB schemas.', status: 'In Progress', assignedAgentId: '3', createdAt: new Date().toISOString() },
                    { id: 'T-002', title: 'Verify UI Consistency', description: 'Check that Habbo Hotel retro aesthetic is applied across all components.', status: 'Pending', assignedAgentId: '6', createdAt: new Date().toISOString() },
                ];
            }
            setTasks(fetchedTasks);
            setIsLoading(false);
        };
        fetchTasks();
    }, []);

    const handleCreateProject = async () => {
        setIsCreating(true);
        try {
            const res = await fetch('/api/nocodb/Projects_Tasks', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    Title: 'New Assigned Project',
                    Description: 'Autogenerated objective from Director Dashboard.',
                    Status: 'Pending'
                })
            });
            if (res.ok) {
                // Refresh list
                const refreshed = await getNocoData('Projects_Tasks');
                if (refreshed && refreshed.length > 0) setTasks(refreshed);
            }
        } catch (e) {
            console.error(e);
        } finally {
            setIsCreating(false);
        }
    };

    return (
        <div className="h-full flex flex-col space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-xl font-bold bg-[#c0c0c0] p-2 inline-block border-[4px] border-[#909090]">ACTIVE PLANS & TASKS</h2>
                <button
                    onClick={handleCreateProject}
                    disabled={isCreating}
                    className={`pixel-btn ${isCreating ? 'bg-gray-500 border-gray-700' : 'bg-green-600 border-green-900 hover:bg-green-500'}`}>
                    {isCreating ? 'Creating...' : 'Create New Project'}
                </button>
            </div>

            <div className="flex-1 bg-[#d3d3d3] border-[6px] border-[#808080] flex flex-col space-y-4 overflow-auto overflow-x-hidden p-6 shadow-inner relative">

                {isLoading && (
                    <div className="absolute inset-0 flex items-center justify-center bg-black/10 z-10">
                        <span className="pixel-box bg-white text-xs animate-pulse">Loading Tasks...</span>
                    </div>
                )}

                {tasks.map(task => (
                    <div key={task.id || (task as any).Id} className="pixel-box bg-white flex flex-col relative group">
                        {/* Folder tab aesthetic */}
                        <div className="absolute -top-6 left-0 bg-yellow-400 border-[4px] border-b-0 border-[#b8860b] px-4 py-1 text-[10px] font-bold">
                            {task.id || `T-${(task as any).Id}`}
                        </div>

                        <div className="flex justify-between items-start mb-2">
                            <h3 className="text-sm text-blue-900 font-bold">{task.title || (task as any).Title}</h3>
                            <span className={`text-[9px] uppercase px-2 py-1 border-[2px] ${task.status === 'Pending' || (task as any).Status === 'Pending' ? 'bg-orange-200 border-orange-500 text-orange-900' :
                                task.status === 'In Progress' || (task as any).Status === 'In Progress' ? 'bg-blue-200 border-blue-500 text-blue-900' :
                                    task.status === 'Completed' || (task as any).Status === 'Completed' ? 'bg-green-200 border-green-500 text-green-900' : 'bg-gray-200 border-gray-500'
                                }`}>
                                {task.status || (task as any).Status || 'Pending'}
                            </span>
                        </div>

                        <p className="text-[10px] text-gray-700 leading-relaxed mb-4 max-w-3xl">
                            {task.description || (task as any).Description}
                        </p>

                        <div className="border-t-[2px] border-dashed border-gray-300 pt-2 flex justify-between items-center bg-gray-50 p-2 border-[2px]">
                            <div className="text-[8px] text-gray-500">
                                Assigned To: <span className="font-bold text-gray-800">Agent {task.assignedAgentId || (task as any).AssignedTo || 'Unassigned'}</span>
                            </div>
                            <div className="flex gap-2">
                                <button className="pixel-btn text-[8px] px-2 py-1 bg-yellow-600 border-yellow-900 hover:bg-yellow-500">Acknowledge</button>
                            </div>
                        </div>
                    </div>
                ))}

            </div>
        </div>
    );
}
